version: "2.1"
services:
  db:
    image: mysql
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: dbTP
      MYSQL_USER: userTP
      MYSQL_ROOT_PASSWORD: tp
    ports:
      - "3307:3307"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
      container_name: nodejs
      build: ./
      ports:
      - "3000:3000"
      volumes:
      - .:/app
      - ./error.log:/usr/src/app/error.log
      links:
      - db
      environment:
        MYSQL_HOST_IP: db


