version: "2.1"
services:
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: dbTP
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: pwd

    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10


  node:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
    environment:
     - DATABASE_HOST=db
    depends_on: 
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
